### PR TITLE
Fixed issue with broken callback. Moved testing to use stubbing

### LINKED ISSUE #2: Last step of the Workflow is not running
It looks like the last step of a given work flow is not running.

Given a workflow that looks like this:
```
class FourStepWorkflow
  include Sidekiq::Worker
  include Sidekiq::SimpleWorkflow

  def perform(*args)
    start_workflow(*args)
  end

  def step_1(_, options)
    logger.info("^^^^^^^^^^^^^^^^^#{self.class} step 1^^^^^^^^^^^^^^^^^^^^^^^")
  end

  def step_2(_, options)
    logger.info("^^^^^^^^^^^^^^^^^#{self.class} step 2^^^^^^^^^^^^^^^^^^^^^^^")
  end

  def step_3(_, options)
    logger.info("^^^^^^^^^^^^^^^^^#{self.class} step 3^^^^^^^^^^^^^^^^^^^^^^^")
  end

  def step_4(_, options)
    logger.info("^^^^^^^^^^^^^^^^^#{self.class} step 4^^^^^^^^^^^^^^^^^^^^^^^")
  end
end
```

When this workflow runs, this output is shown in the logs:
```
2021-09-09T18:35:31.552Z pid=21668 tid=le8 class=FourStepWorkflow jid=297b08304ae95c20ccb81605 INFO: start
2021-09-09T18:35:31.649Z pid=21668 tid=lpc class=ExampleWorker jid=08979bd4c37bd41a7b16c867 INFO: start
2021-09-09T18:35:31.762Z pid=21668 tid=lpc class=ExampleWorker jid=08979bd4c37bd41a7b16c867 INFO: ~~~~~~~~~~ExampleWorker is running~~~~~~~~~~~~~~
2021-09-09T18:35:31.762Z pid=21668 tid=lpc class=ExampleWorker jid=08979bd4c37bd41a7b16c867 elapsed=0.113 INFO: done
2021-09-09T18:35:31.763Z pid=21668 tid=le8 class=FourStepWorkflow jid=297b08304ae95c20ccb81605 INFO: ^^^^^^^^^^^^^^^^^FourStepWorkflow step 1^^^^^^^^^^^^^^^^^^^^^^^
2021-09-09T18:35:31.764Z pid=21668 tid=lrw class=Sidekiq::SimpleWorkflow::NoOpWorker jid=21bd04f1bf4420ffad96febd bid=sLoK7o3bBqdpmg INFO: start
2021-09-09T18:35:31.765Z pid=21668 tid=le8 class=FourStepWorkflow jid=297b08304ae95c20ccb81605 elapsed=0.212 INFO: done
2021-09-09T18:35:31.767Z pid=21668 tid=lqg class=Sidekiq::Batch::Callback jid=7680a986ec1c09fb136c4a55 INFO: start
2021-09-09T18:35:31.768Z pid=21668 tid=lrw class=Sidekiq::SimpleWorkflow::NoOpWorker jid=21bd04f1bf4420ffad96febd bid=sLoK7o3bBqdpmg elapsed=0.003 INFO: done
2021-09-09T18:35:31.769Z pid=21668 tid=lqg class=Sidekiq::Batch::Callback jid=7680a986ec1c09fb136c4a55 INFO: ^^^^^^^^^^^^^^^^^FourStepWorkflow step 2^^^^^^^^^^^^^^^^^^^^^^^
2021-09-09T18:35:31.769Z pid=21668 tid=lt0 class=Sidekiq::SimpleWorkflow::NoOpWorker jid=95705a661fed57796fe5f376 bid=VJ2u3UyoZyoqNA INFO: start
2021-09-09T18:35:31.772Z pid=21668 tid=lt0 class=Sidekiq::SimpleWorkflow::NoOpWorker jid=95705a661fed57796fe5f376 bid=VJ2u3UyoZyoqNA elapsed=0.003 INFO: done
2021-09-09T18:35:31.772Z pid=21668 tid=ltc class=Sidekiq::Batch::Callback jid=c4f68a813b851d5e6e3879c7 INFO: start
2021-09-09T18:35:31.772Z pid=21668 tid=lsc class=Sidekiq::Batch::Callback jid=5c122e59294b80fb0600c393 INFO: start
2021-09-09T18:35:31.772Z pid=21668 tid=lqg class=Sidekiq::Batch::Callback jid=7680a986ec1c09fb136c4a55 elapsed=0.006 INFO: done
2021-09-09T18:35:31.775Z pid=21668 tid=ltc class=Sidekiq::Batch::Callback jid=c4f68a813b851d5e6e3879c7 INFO: ^^^^^^^^^^^^^^^^^FourStepWorkflow step 3^^^^^^^^^^^^^^^^^^^^^^^
2021-09-09T18:35:31.776Z pid=21668 tid=lsc class=Sidekiq::Batch::Callback jid=5c122e59294b80fb0600c393 elapsed=0.004 INFO: done
2021-09-09T18:35:31.777Z pid=21668 tid=lso class=Sidekiq::Batch::Callback jid=9d6409d6fbb27c9cebbf9cdc INFO: start
2021-09-09T18:35:31.778Z pid=21668 tid=ltc class=Sidekiq::Batch::Callback jid=c4f68a813b851d5e6e3879c7 elapsed=0.006 INFO: done
2021-09-09T18:35:31.778Z pid=21668 tid=m2c class=Sidekiq::Batch::Callback jid=63733bddadb0c4479f050b72 INFO: start
2021-09-09T18:35:31.780Z pid=21668 tid=lso class=Sidekiq::Batch::Callback jid=9d6409d6fbb27c9cebbf9cdc elapsed=0.003 INFO: done
2021-09-09T18:35:31.781Z pid=21668 tid=m0w class=Sidekiq::Batch::Callback jid=a3ebf5a728f98bc4f05dc28a INFO: start
2021-09-09T18:35:31.781Z pid=21668 tid=m2c class=Sidekiq::Batch::Callback jid=63733bddadb0c4479f050b72 elapsed=0.003 INFO: done
2021-09-09T18:35:31.783Z pid=21668 tid=m0w class=Sidekiq::Batch::Callback jid=a3ebf5a728f98bc4f05dc28a elapsed=0.002 INFO: done
```

Here is an example project that replicates the issue
https://github.com/mpmenne/sidekiq-simple-workflow-example

### PR DESCRIPTION
**Pull request by mpmenne**
This PR fixes #2 .  Essentially the code for steps 2-10 were creating a callback to a method that did not exist.  The unit specs did not catch this because we were initially calling each workflow step individually.  Subsequently we were directly calling the callback and masking the bug.

- [x] Corrected an issue where the callback was referencing a non existent method
- [x] Changed the test code to use `batch.status.join` instead of directly calling the callback
- [x] Moved tests to use stubbing since `batch.status.join` drains the queue.

### CODE REVIEW

File: lib/sidekiq/simple_workflow.rb [hunk 1]
```diff
@@ -51,7 +51,7 @@ def step_1_batch(status, args)
             next_step_method = step_method_name(step_number + 1)
             if respond_to? next_step_method
 
-              callback = "#{self.class}##{next_step_method}"
+              callback = callback_method(step_number + 1)
```
Comment (mpmenne) [inline lib/sidekiq/simple_workflow.rb:54]: this is where the callback was messed up
